# Generated by Django 5.1.4 on 2026-02-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_size_when_color_null',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_color_when_size_null',
        ),
    ]
