# Generated by Django 6.0.5 on 2026-05-28 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('color', 'Color')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('filterable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'label'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_color_size_variant',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_signature',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'attribute_signature'], name='product_pro_product_b9f28f_idx'),
        ),
        migrations.AddIndex(
            model_name='variantattributedefinition',
            index=models.Index(fields=['key'], name='product_var_key_5c9db8_idx'),
        ),
        migrations.AddIndex(
            model_name='variantattributedefinition',
            index=models.Index(fields=['filterable', 'position'], name='product_var_filtera_ee379e_idx'),
        ),
    ]
