# Generated by Django 5.1.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0002_remove_productvariant_unique_product_size_when_color_null_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_images",
                to="product.productcolor",
                to_field="color_code",
            ),
        ),
    ]
