# Generated by Django 5.1.4 on 2026-01-11 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redeem_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type', models.CharField(blank=True, choices=[('amount', 'Amount'), ('percentage', 'Percentage')], max_length=10, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('minimum', models.IntegerField(blank=True, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('used', models.IntegerField(blank=True, default=0, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionuid', models.CharField(blank=True, max_length=225, null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('verified', 'Verified'), ('proceed', 'Proceed'), ('packed', 'Packed'), ('delivered', 'Delivered'), ('successful', 'Successful'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('total_amt', models.FloatField()),
                ('sub_total', models.FloatField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('redeem_data', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_json', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('costumer_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('shipping', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.deliveryaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Saled_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('total', models.FloatField()),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.product')),
                ('variant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.productvariant')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.sales')),
            ],
        ),
    ]
