# Generated by Django 6.0.5 on 2026-05-29 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='pickdrop', max_length=50)),
                ('provider_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_url', models.URLField(blank=True, max_length=500, null=True)),
                ('waybill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('label_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('booked', 'Booked'), ('assigned', 'Assigned'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('sync_failed', 'Sync failed')], default='pending', max_length=30)),
                ('provider_status', models.CharField(blank=True, max_length=100, null=True)),
                ('package_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pickup_payload', models.JSONField(blank=True, default=dict)),
                ('drop_payload', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='sales.sales')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('provider_status', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sales.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['provider', 'provider_order_id'], name='sales_shipm_provide_0245d3_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='sales_shipm_trackin_14c81b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='sales_shipm_status_bd8bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['event_type'], name='sales_shipm_event_t_7bdbf1_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['provider_status'], name='sales_shipm_provide_7d871c_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['created_at'], name='sales_shipm_created_ee84d0_idx'),
        ),
    ]
