# Generated by Django 5.1.4 on 2026-02-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
