# Generated by Django 6.0.5 on 2026-05-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_shipment_shipmentevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='transactionuid',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
