# Generated by Django 5.1.4 on 2026-02-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='delivery_delay_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
