# Generated by Django 5.1.7 on 2026-02-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteviewlog',
            name='enclg',
        ),
        migrations.RemoveField(
            model_name='siteviewlog',
            name='encsh',
        ),
        migrations.RemoveField(
            model_name='siteviewlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='siteviewlog',
            name='region',
        ),
    ]
