# Generated by Django 5.1.4 on 2026-02-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_siteviewlog_enclg_remove_siteviewlog_encsh_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliveryaddress',
            name='unique_default_address_per_user',
        ),
    ]
