# Generated by Django 5.1.4 on 2026-02-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_notes_booking_admin_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='measurement_type',
            field=models.CharField(choices=[('in_store', 'In-Store'), ('home_visit', 'Home Visit'), ('self', 'Self')], default='in_store', max_length=20),
        ),
    ]
