# Generated by Django 5.1.4 on 2026-02-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bill_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
